services:
  - type: web
    name: wbgnews
    runtime: python3
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 -b 0.0.0.0:$PORT app:app
    plan: free
    branch: main
    healthCheckPath: /api/health
    envVars:
      - key: FLASK_DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: "3.9.16"
    scaling:
      minInstances: 1
      maxInstances: 1
    autoDeploy: true
    preDeployCommand: echo "Starting WbgNews deployment..."
    disk:
      name: wbgnews-disk
      sizeGB: 1
      mountPath: /opt/render/project/src
